# -*- coding: utf-8 -*-
"""
This is a standalone utility for deleting certficiates generated by create_pdfs.py.
"""
from argparse import ArgumentParser, RawTextHelpFormatter
import logging
import sys

from gen_cert import CertificateGen, TMP_GEN_DIR
import settings


logging.config.dictConfig(settings.LOGGING)
LOG = logging.getLogger('certificates.delete_pdfs')

description = """
  Delete sample certificates generated by create_pdfs.py
"""


def parse_args(args=sys.argv[1:]):
    parser = ArgumentParser(description=description,
                            formatter_class=RawTextHelpFormatter)

    parser.add_argument('-d', '--download-uuid', help='certificate download uuid', required=True)
    parser.add_argument('-v', '--verify-uuid', help='certificate verify uuid', required=True)
    return parser.parse_args()


def main():
    """
    Deletes a certificate's files from S3 and the local filesystem.
    """
    pdf_dir = TMP_GEN_DIR

    cert = CertificateGen(
        'course-v1:edX+DemoX+Demo_Course',
        aws_id=settings.CERT_AWS_ID,
        aws_key=settings.CERT_AWS_KEY,
        dir_prefix=pdf_dir,
    )
    cert.delete_certificate(args.download_uuid, args.verify_uuid)


if __name__ == '__main__':
    args = parse_args()
    main()
